<?php
/**
* Implements hook_element_info_alter().
*
* Sets the text format processor to a custom callback function.
* This code is taken from the Better Formats module.
*/
function textchanger_element_info_alter(&$type) {
  if (isset($type['text_format']['#process'])) {
    foreach ($type['text_format']['#process'] as &$callback) {
      if ($callback === 'filter_process_format') {
        $callback = 'textchanger_filter_process_format';
      }
    }
  }
}

/**
* Callback for textchanger_element_info_alter().
*/
function textchanger_filter_process_format($element) {
  $element = filter_process_format($element);
  // Change input format to "Full HTML" for Vidoe fields of Video nodes
  if ($element['#bundle'] == 'video' && $element['#field_name'] == 'video') {
    $element['format']['format']['#default_value'] = 'full_html';
  }
  return $element;
}