<?php
  //color schemes
  $info = array(

  // Available colors and color labels used in theme.
  'fields' => array(
    'base' => t('Base color'),
    'link' => t('Link color'),
    'text' => t('Text color'),
    'background' => t('Background color'),
  ),

  'schemes' => array(
    'default' => array(
      'title' => t('Orange (Default)'),
      'colors' => array(
        'base' => '#ff9900',
        'link' => '#ff9900',
        'text' => '#8c8c8c',
        'background' => '#ffffff',
      ),
    ),

    'scheme2' => array(
      'title' => t('Color 2'),
      'colors' => array(
        'base' => '#b1de00',
        'link' => '#b1de00',
        'text' => '#8c8c8c',
        'background' => '#ffffff',
      ),
    ),

    'scheme3' => array(
      'title' => t('Color 3'),
      'colors' => array(
        'base' => '#71e555',
        'link' => '#71e555',
        'text' => '#8c8c8c',
        'background' => '#ffffff',
      ),
    ),

    'scheme4' => array(
      'title' => t('Color 4'),
      'colors' => array(
        'base' => '#33ca6f',
        'link' => '#33ca6f',
        'text' => '#8c8c8c',
        'background' => '#ffffff',
      ),
    ),

    'scheme5' => array(
      'title' => t('Color 5'),
      'colors' => array(
        'base' => '#1d9d9e',
        'link' => '#1d9d9e',
        'text' => '#8c8c8c',
        'background' => '#ffffff',
      ),
    ),

    'scheme6' => array(
      'title' => t('Color 6'),
      'colors' => array(
        'base' => '#0065ff',
        'link' => '#0065ff',
        'text' => '#8c8c8c',
        'background' => '#ffffff',
      ),
    ),

    'scheme7' => array(
      'title' => t('Color 7'),
      'colors' => array(
        'base' => '#3200ff',
        'link' => '#3200ff',
        'text' => '#8c8c8c',
        'background' => '#ffffff',
      ),
    ),

    'scheme8' => array(
      'title' => t('Color 8'),
      'colors' => array(
        'base' => '#cb00ff',
        'link' => '#cb00ff',
        'text' => '#8c8c8c',
        'background' => '#ffffff',
      ),
    ),

    'scheme9' => array(
      'title' => t('Color 9'),
      'colors' => array(
        'base' => '#ff0098',
        'link' => '#ff0098',
        'text' => '#8c8c8c',
        'background' => '#ffffff',
      ),
    ),

    'scheme10' => array(
      'title' => t('Color 10'),
      'colors' => array(
        'base' => '#ff0000',
        'link' => '#ff0000',
        'text' => '#8c8c8c',
        'background' => '#ffffff',
      ),
    ),

    'dark1' => array(
      'title' => t('Dark 1'),
      'colors' => array(
        'base' => '#00327d',
        'link' => '#00327d',
        'text' => '#505050',
        'background' => '#9f9f9f',
      ),
    ),

    'dark2' => array(
      'title' => t('Dark 2'),
      'colors' => array(
        'base' => '#18007d',
        'link' => '#18007d',
        'text' => '#505050',
        'background' => '#9f9f9f',
      ),
    ),

    'dark3' => array(
      'title' => t('Dark 3'),
      'colors' => array(
        'base' => '#63007d',
        'link' => '#63007d',
        'text' => '#505050',
        'background' => '#9f9f9f',
      ),
    ),

    'dark4' => array(
      'title' => t('Dark 4'),
      'colors' => array(
        'base' => '#7d004a',
        'link' => '#7d004a',
        'text' => '#505050',
        'background' => '#9f9f9f',
      ),
    ),

    'dark5' => array(
      'title' => t('Dark 5'),
      'colors' => array(
        'base' => '#7d0000',
        'link' => '#7d0000',
        'text' => '#505050',
        'background' => '#9f9f9f',
      ),
    ),

    'dark6' => array(
      'title' => t('Dark 6'),
      'colors' => array(
        'base' => '#7d4b00',
        'link' => '#7d4b00',
        'text' => '#505050',
        'background' => '#9f9f9f',
      ),
    ),

    'dark7' => array(
      'title' => t('Dark 7'),
      'colors' => array(
        'base' => '#637d00',
        'link' => '#637d00',
        'text' => '#505050',
        'background' => '#9f9f9f',
      ),
    ),

    'dark8' => array(
      'title' => t('Dark 8'),
      'colors' => array(
        'base' => '#187d00',
        'link' => '#187d00',
        'text' => '#505050',
        'background' => '#9f9f9f',
      ),
    ),

    'dark9' => array(
      'title' => t('Dark 9'),
      'colors' => array(
        'base' => '#007d32',
        'link' => '#007d32',
        'text' => '#505050',
        'background' => '#9f9f9f',
      ),
    ),

    'dark10' => array(
      'title' => t('Dark 10'),
      'colors' => array(
        'base' => '#007c7d',
        'link' => '#007c7d',
        'text' => '#505050',
        'background' => '#9f9f9f',
      ),
    ),
  ),

  // Images to copy over
  'copy' => array(
    'logo.png',
  ),

  // CSS files (excluding @import) to rewrite with new color scheme.
  'css' => array(
    'color/color_module.css',
  ),

  // Color areas to fill (x, y, width, height)
  'fill' => array(
  ),

  // Gradient definitions.
  'gradients' => array(
  ),

  // Coordinates of all the theme slices (x, y, width, height)
  // with their filename as used in the stylesheet.
  'slices' => array(
  ),

  // color preview css
  'preview_css' => '',

  // Base file for image generation
  'base_image' => 'logo.png',

  //	blend target
	'blend_target' => '#ffffff'
);
?>